# Generated by Django 3.1.2 on 2021-05-23 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='update_date',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
    ]
